unlet! skip_defaults_vim
source $VIMRUNTIME/defaults.vim

autocmd BufWritePost * silent !ctags --exclude=@.ctagsignore --recurse 2> /dev/null
autocmd CursorHold * checktime
autocmd VimEnter * copen | wincmd k | vsplit

let netrw_liststyle = 3

set autoread
set colorcolumn=81
set exrc
set hlsearch
set ignorecase
set number
set path=**
set smartcase
set wildignorecase
