autocmd BufWritePost * silent !ctags --exclude=@.ctagsignore --recurse
autocmd CursorHold * checktime
autocmd VimEnter * copen | wincmd k | vsplit

filetype plugin indent on

let g:netrw_banner = 0
let g:netrw_liststyle = 3
let g:netrw_winsize = 16

set autoread
set colorcolumn=81
set exrc
set hlsearch
set ignorecase
set number
set path=**
set ruler
set smartcase
set wildignorecase
set wildmenu

syntax enable
